export enum FingerType {
    RIGHTTHUMB = "RIGHT THUMB",
    RIGHTINDEX = "RIGHT INDEX",
    RIGHTMIDDLE = "RIGHT MIDDLE FINGER",
    RIGHTRING = "RIGHT RING FINGER",
    RIGHTPINKY = "RIGHT PINKY",
    LEFTTHUMB = "LEFT THUMB",
    LEFTINDEX = "LEFT INDEX",
    LEFTMIDDLE = "LEFT MIDDLE FINGER",
    LEFTRING = "LEFT RING FINGER",
    LEFTPINKY = "LEFT PINKY"
  }